name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Obtener el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v2

    # Paso 2: Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Paso 3: Instalar dependencias de Python
    - name: Install dependencies
      run: |
        cd app  # Nos movemos al directorio donde está el archivo requirements.txt
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Paso 4: Ejecutar las pruebas
    - name: Run tests
      run: |
        pytest tests/


